### ISSUE TITLE
Todo Project - Cat Application

### ISSUE THREAD

**Issue by danielrgn** [danielrgn/cat-application#1]
- [x] Criar consumer
   - [x] Configurar docker
   - [x] Configurar Spring cloud task
   - [x] Configurar Feign client
   - [x] Criar serviços para consumir api [The cat API](https://thecatapi.com/)
        - [x] Consumir raças
        - [x] Consumir imagens
             - [x] por raças
             - [x] por categorias (óculos e chapéus)
   - [x] Validar registros salvos
   - [x] Adicionar logs
   - [x] Criar testes unitários

- [ ] Criar api
  - [x] Adicionar módulo API
  - [x] Listar todas as raças
  - [x] Listar uma raça
  - [x] Listar as raças a partir de um temperamento
  - [x] Listar as raças a partir de uma origem
  - [x] Expor métricas de execução
  - [x] Criar coleção no Postman para consumir as APIs
  - [x] Swagger
  - [x] Criar testes unitários
  - [x] Criar testes integrados
  - [ ] Ferramenta de logs (exemplos: Elastic Search, Splunk, Graylog ou similar)
  - [ ] Ferramenta de métricas para sua infraestrutura (exemplos: Prometheus, Zabbix, cloudwatch ou similar)
  
- [x] README
    - [x] Documentação do projeto
    - [x] Documentação API
    - [x] Documentação arquitetura
    - [x] Documentação de como subir e testar localmente
    - [x] Utilizar técnicas ou descreva formas de aplicar os temas qualidade e teste na sua aplicação
    - [x] Prints dos logs e dashboards
